services:
  medusa:
    build:
      context: ../..
      dockerfile: apps/medusa/Dockerfile
      target: dev
    env_file:
      - .env.docker
    environment:
      NODE_ENV: development
    working_dir: /app/apps/medusa
    command: >
      sh -c "chmod +x ./start.sh && ./start.sh"
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app/apps/medusa
      - ../../packages/medusa-plugin-shopify:/app/packages/medusa-plugin-shopify
      - medusa_root_node_modules:/app/node_modules
      - medusa_app_node_modules:/app/apps/medusa/node_modules
      - medusa_plugin_node_modules:/app/packages/medusa-plugin-shopify/node_modules
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: medusa
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - medusa_db_data:/var/lib/postgresql/data

  redis:
    profiles:
      - redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - medusa_redis_data:/data

volumes:
  medusa_db_data:
  medusa_redis_data:
  medusa_root_node_modules:
  medusa_app_node_modules:
  medusa_plugin_node_modules:
